version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.7.0
    networks:
      - kafka-standalone
    ports:
      - 2181:2181
    volumes:
      - /var/lib/zookeeper/node_1/data:/data
      - /var/lib/zookeeper/node_1/dataLogDir:/datalog
      - /var/lib/zookeeper/node_1/logs:/logs
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    hostname: zookeeper
    
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.1.0
    networks:
      - kafka-standalone
    ports:
      - 9092:9092
      - 9999:9999
      - 8778:8778
    volumes:
      - /var/lib/kafka/node_1:/bitnami/kafka
      - ${PWD}/jolokia-agent.jar:/opt/bitnami/kafka/libs/jolokia-agent.jar
      # - ${PWD}/kafka-server-start.sh:/opt/bitnami/kafka/bin/kafka-server-start.sh
    env_file:
      - kafka.env
    depends_on:
      - zookeeper

networks:
  kafka-standalone:
