---
version: "3"
services:
  jenkins:
    container_name: jenkins-blueocean
    image: jenkinsci/blueocean
    restart: unless-stopped
    networks:
      - jenkins-network
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/lib/jenkins:/var/jenkins_home

networks:
  jenkins-network:
    name: "jenkins"
